In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pylab as plt

In [4]:
from matplotlib.pylab import rcParams

In [5]:
rcParams['figure.figsize'] = 300,150

In [6]:
dateparse = lambda dates: pd.datetime.strptime(dates, '%d-%b-%y')
data = pd.read_csv('Cleaner_data.csv',parse_dates=['Donation_Date'], index_col='Donation_Date',date_parser=dateparse)

In [11]:
data.sample(10)

,row ID,Financial_Year,Branch_Code,Sequence_1,Sequence_2,Donation_type,Donor_Age,Gender,Blood_Group_Code,Donor_Weight,Donor_Temperature,Donor_Pulse,Donor_Hemoglobin,Donor_Blood_Pressure,Test_1,C1,Test_2,C2,Test_3,Test_4
Donation_Date,,,,,,,,,,,,,,,,,,,,
2013-10-17,15117,14,BRC-01,92896,15117.0,R,28.0,M,3,65.0,37.0,72,14.0,120/80,0.143,N,0.211,N,N,N
2013-10-28,16725,14,BRC-01,94504,16725.0,R,23.0,M,5,60.0,37.0,72,13.0,120/80,0.152,N,0.244,N,N,N
2016-04-30,112054,16,BRC-01,33727,31384.0,M,31.0,M,3,70.0,37.0,72,14.0,110/90,0.084,N,0.221,N,N,N
2016-07-28,122561,17,BRC-01,4092,3637.0,R,27.0,M,5,80.0,37.0,72,13.0,120/80,0.183,N,0.242,N,N,N
2015-01-20,65418,15,BRC-01,22331,21099.0,R,22.0,M,1,80.0,37.0,72,13.0,120/80,0.351,N,0.261,N,N,N
2015-06-13,78981,15,BRC-01,35894,34662.0,T,33.0,M,1,67.0,37.0,76,14.0,120/80,0.414,N,0.201,N,N,N
2017-08-08,163633,18,BRC-01,5007,4219.0,T,27.0,M,4,63.0,37.0,72,14.0,80/120,0.103,N,0.174,N,N,N
2015-04-27,74533,15,BRC-01,31446,30214.0,R,28.0,M,7,90.0,37.0,72,13.0,120/80,0.432,N,0.163,N,N,N
2015-08-23,85982,16,BRC-01,7655,5311.0,R,19.0,M,5,95.0,37.0,78,13.0,120/80,0.573,N,0.234,N,N,N
2018-06-04,217177,18,BRC-02,24636,14954.0,R,28.0,M,5,72.0,37.0,72,13.0,120/80,0.122,N,0.100,N,N,N

In [8]:
data[1]

KeyError: 1

In [9]:
data.head().next()

AttributeError: 'DataFrame' object has no attribute 'next'