In [1]:
import pandas as pd
import re

df = pd.read_csv('Clean_data.csv')
df.head()

,row ID,Financial_Year,Branch_Code,Sequence_1,Sequence_2,Donation_type,Donor_Age,Donation_Date,Gender,Blood_Group_Code,...,Donor_Temperature,Donor_Pulse,Donor_Hemoglobin,Donor_Blood_Pressure,Test_1,C1,Test_2,C2,Test_3,Test_4
0,1,14,BRC-01,345,1.0,R,24.0,1-Jul-13,M,5,...,37.0,72,13.0,120/80,0.121,N,0.224,N,R,N
1,2,14,BRC-01,346,2.0,R,33.0,1-Jul-13,M,3,...,37.0,72,13.0,120/80,0.122,N,0.222,N,N,N
2,3,14,BRC-01,347,3.0,R,28.0,1-Jul-13,M,5,...,37.0,72,13.0,120/80,0.123,N,0.221,N,N,N
3,4,14,BRC-01,348,4.0,R,20.0,1-Jul-13,M,3,...,37.0,72,13.0,120/80,0.123,N,0.242,N,N,N
4,5,14,BRC-01,349,5.0,T,22.0,1-Jul-13,M,7,...,37.0,72,13.0,120/80,0.124,N,0.243,N,N,N

In [2]:
cols = ['row ID', 'Financial_Year','Branch_Code', 'Sequence_1','Sequence_2', 'Donation_type',
        'Donor_Age','Gender','Donor_Weight',
        'Donor_Temperature', 'Donor_Pulse', 'Donor_Hemoglobin', 'Donor_Blood_Pressure',
        'Test_1','C1','Test_2','C2','Test_3','Test_4']
df.drop(cols,axis=1, inplace=True)
df.isnull().sum()

Donation_Date       0
Blood_Group_Code    0
dtype: int64

In [16]:
df = df.groupby('Donation_Date')
['Donation_Blood_Group'].sum().reset_index()
df.set_index('Donation_Date')

AttributeError: Cannot access callable attribute 'groupby' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [14]:
df['26-jul-17':]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.range.RangeIndex'> with these indexers [26-jul-17] of <class 'str'>